/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSegmentationImport } from './routes/_layout/segmentation'
import { Route as LayoutProjectInfoImport } from './routes/_layout/project-info'
import { Route as LayoutAboutMeImport } from './routes/_layout/about-me'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSegmentationRoute = LayoutSegmentationImport.update({
  path: '/segmentation',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectInfoRoute = LayoutProjectInfoImport.update({
  path: '/project-info',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutMeRoute = LayoutAboutMeImport.update({
  path: '/about-me',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about-me': {
      preLoaderRoute: typeof LayoutAboutMeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/project-info': {
      preLoaderRoute: typeof LayoutProjectInfoImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/segmentation': {
      preLoaderRoute: typeof LayoutSegmentationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAboutMeRoute,
    LayoutProjectInfoRoute,
    LayoutSegmentationRoute,
    LayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
